# Copyright (c) Meta Platforms, Inc. and affiliates. All rights reserved.
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""All prompt templates, grouped by purpose."""

from __future__ import annotations

from gaia2_mt.prompts.translation import (
    EXPECTED_RESPONSE_REVIEW_PROMPT,
    EXPECTED_RESPONSE_REVIEW_SYSTEM_PROMPT,
    ORACLE_ARG_REVIEW_PROMPT,
    ORACLE_ARG_REVIEW_SYSTEM_PROMPT,
    ORACLE_ARG_TRANSLATION_PROMPT,
    ORACLE_ARG_TRANSLATION_SYSTEM_PROMPT,
    POST_EDIT_PROMPT,
    POST_EDIT_SYSTEM_PROMPT,
    RESPONSE_TRANSLATION_PROMPT,
    RESPONSE_TRANSLATION_SYSTEM_PROMPT,
    TRANSLATION_PROMPT,
    TRANSLATION_REVIEW_PROMPT,
    TRANSLATION_REVIEW_SYSTEM_PROMPT,
    TRANSLATION_SYSTEM_PROMPT,
)


__all__ = [
    "EXPECTED_RESPONSE_REVIEW_PROMPT",
    "EXPECTED_RESPONSE_REVIEW_SYSTEM_PROMPT",
    "ORACLE_ARG_REVIEW_PROMPT",
    "ORACLE_ARG_REVIEW_SYSTEM_PROMPT",
    "ORACLE_ARG_TRANSLATION_PROMPT",
    "ORACLE_ARG_TRANSLATION_SYSTEM_PROMPT",
    "POST_EDIT_PROMPT",
    "POST_EDIT_SYSTEM_PROMPT",
    "RESPONSE_TRANSLATION_PROMPT",
    "RESPONSE_TRANSLATION_SYSTEM_PROMPT",
    "TRANSLATION_PROMPT",
    "TRANSLATION_REVIEW_PROMPT",
    "TRANSLATION_REVIEW_SYSTEM_PROMPT",
    "TRANSLATION_SYSTEM_PROMPT",
]
